[package]
name = "pkg1"
version = "0.1.0"
authors = ["pdrob10500"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.20-rc.1"
csv = "~1.1.6"
serde = {version = "1.0.140", features = ["derive"]}
